# Generated by Django 4.2 on 2024-08-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefactors', '0001_initial'),
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='benefactors.benefactor'),
        ),
        migrations.DeleteModel(
            name='Benefactor',
        ),
    ]
