# Generated by Django 4.2 on 2024-08-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_alter_task_assigned_benefactor_delete_benefactor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
